apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dev
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      namespace: dev
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
  replicas: 3
  selector: # help minotor when large number of pods
    matchLabels:
      app: myapp
