apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    role: redis
    tier: back
  # namespace: instavote
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      # type: ClusterIP # default
