apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
  # namespace: instavote
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  minReadySeconds: 10
  selector:
    matchLabels:
      role: results
    matchExpressions:
      - { key: version, operator: In, values: [v1, v2, v3, latest] }
  template:
    metadata:
      name: results
      labels:
        app: python
        role: results
        version: latest
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote-result:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              protocol: TCP
