apiVersion: v1
kind: Service
metadata:
  name: results
  labels:
    role: results
spec:
  selector:
    role: results
    version: latest
  ports:
    - port: 82
      targetPort: 80
      nodePort: 30001 # if NodePort
  type: NodePort
  # externalIPs:
  #   - null
