apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  log.level: err
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iniconfig
data:
  config.ini: |-
    [unusual]
    greeting=hello
    onoff=true
    anumber=3
