apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  CONFIG_FILE: "/etc/flask-config/feature.flags"
  feature.flags: |-
    [features]
    greeting=hello
    debug=true
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: quay.io/kubernetes-for-developers/flask:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
          volumeMounts:
            - name: config
              mountPath: /etc/flask-config
      volumes:
        - name: config
          configMap:
            name: flask-config
