apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  # concurrencyPolicy: Allow # Allow, Forbid, Replace
  # suspend: False
  # successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: simple
              image: busybox
              command: ["/bin/sh", "-c", "echo", "'hello world'"]
          restartPolicy: OnFailure
