apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      labels:
        app: my-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job