apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: dev
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-pod
      namespace: dev
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 3
